### ISSUE TITLE
feature request: bind to specific address

### ISSUE THREAD

**Issue by 0x6273** [robertohuertasm/microserver#11]
Currently, only binding to all IPv4 interfaces (0.0.0.0) is supported. I would like to have the option to bind to only a specific address, perhaps via a `--bind` command line argument.

This would allow for:
- Only binding to the loopback interface (`--bind 127.0.0.1`)
- IPv6 support (`--bind [::]`)

**Comment by robertohuertasm** [comment]
Thanks for the suggestion. I've already published v0.2.0
