### ISSUE TITLE
Unable to serve WOFF2 files?

### ISSUE THREAD

**Issue by fosskers** [robertohuertasm/microserver#14]
While this works fine in Chromium, on Firefox I get:

> downloadable font: rejected by sanitizer

when attempting to serve `.woff2` files. Any ideas why this might be happening?

**Comment by robertohuertasm** [comment]
Hi @fosskers it seems to be related to a feature in Firefox. Check [this issue & solution](https://support.mozilla.org/en-US/questions/913498).

> there is something wrong with the layout (contents) of the fontfile. This is a protection against bad or malicious font files. It is probably possible to disable the sanitizer by setting the pref gfx.downloadable_fonts.sanitize to false in about:config but then you are no longer protected.

Have you tried this?

**Comment by fosskers** [comment]
The issue is now mysteriously gone :thinking: Not sure what changed, but thanks for looking into it.
